name: Test ARC Runners
on: [push]

jobs:
  build:
    runs-on: arc-runner-set # Use the runner scale set name (not the namespace)
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run a script
        run: echo "Hello from ARC Runner!"
      - name: List files
        run: ls -la
      - name: Show current env
        run: env